title: xeb.ai
email: xebxeb@gmail.com
description: >- 
  Training neural networks past my bedtime.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xeb.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xeb
github_username:  xeb
domain: xeb.github.io

markdown: kramdown
github:
    is_project_page: false

remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

show_downloads: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
